### This is the main way to configure the application (other than annotations).
### This file is in Yaml format but you can also configure spring boot using the traditional
### Java properties file format. 


### This is the main way to configure the application (other than annotations).
### This file is in Yaml format but you can also configure spring boot using the traditional
### Java properties file format. 


spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    consumer:
      topic-data-seriesupdate: topic-data-seriesupdate
      topic-kite-tick: topic-kite-tick
      groupid-seriesupdate: group-id-series-05
      groupid_tick: group-id-tick-06
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      from:
        beginning: true
        groupid: group-id-series-07
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      topic-kite-tick: topic-kite-tick
      topic-data-seriesupdate: topic-data-seriesupdate
      topic-kite-tradeorder: topic-kite-tradeorder
     
      
  profiles: dev
  
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hc4

server:
  address: 127.0.0.1
  port: 9012

tick:
  file:
    Serializer: /Users/lalitsingh/data/TestData
  barsize: 60
  maxserializetick: 1024
supertrend:
  bandSize: 3
  smaSize: 7
  csvPath: /Users/lalitsingh/data/csv/
  maxBarCount: 20
