### This is the main way to configure the application (other than annotations).
### This file is in Yaml format but you can also configure spring boot using the traditional
### Java properties file format. 


### This is the main way to configure the application (other than annotations).
### This file is in Yaml format but you can also configure spring boot using the traditional
### Java properties file format. 


selector: 
  max-instrument-price-per-stock: 1000
  max-total-price: 800000
  order-quantity: 80
server: 
  address: "127.0.0.1"
  port: 9012
spring: 
  data: 
    mongodb: 
      database: hc4
      host: localhost
      port: 27017
  kafka: 
    bootstrap-servers: "localhost:9092,localhost:9093,localhost:9094"
    consumer: 
      auto-offset-reset: latest
      from: 
        beginning: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      topic-data-seriesupdate: topic-data-seriesupdate
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer: 
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      topic-data-seriesupdate: topic-data-seriesupdate
      topic-kite-tradeorder: topic-kite-tradeorder
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  profiles: dev
supertrend: 
  bandSize: 3
  csvPath: /Users/lalitsingh/data/csv/
  maxBarCount: 20
  smaSize: 7
  userid: WU6870
tick: 
  barsize: 60
  file: 
    Serializer: /Users/lalitsingh/data/TestData
  maxserializetick: 1024
